# For more information: https://laravel.com/docs/sail
services:
    softioc:
        image: slominskir/softioc:1.1.0
        tty: true
        stdin_open: true
        hostname: softioc
        container_name: meters-softioc
        ports:
            - "5064:5064/tcp"
            - "5065:5065/tcp"
            - "5064:5064/udp"
            - "5065:5065/udp"
        volumes:
            - ./run/softioc/db:/db
            - ./run/softioc/scripts:/scripts
        networks:
            - sail
    epics2web:
        image: slominskir/epics2web:1.13.0
        hostname: epics2web
        container_name: meters-epics2web
        environment:
            EPICS_CA_ADDR_LIST: softioc
        depends_on:
            -   softioc
        ports:
            - 8080:8080
        networks:
            - sail
    web:
        image: 'jeffersonlab/cedlib:1.3'
        ports:
            - '80:80'
            - '443:443'
        environment:
            WWWUSER: '${WWWUSER}'
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
        container_name: meters-app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - sail
    mysql:
        image: 'mysql/mysql-server:8.0'
        hostname: mysql
        container_name: meters-db
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './run/var/mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    mailhog:
        image: mailhog/mailhog
        container_name: meters-mail
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        logging:
            driver: 'none'
        networks:
            - sail
        ports:
            - "8003:1025"
            - "8100:8025"
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
